name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typescript:
    name: Test Typescript side
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: Run npm test
        run: |
          node --version
          yarn i
          yarn test