name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  typescript:
    name: All tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: yarn run test
        run: |
          node --version
          yarn
          yarn test